kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-pubsub-0
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pubsub"
