# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='state_value.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11state_value.proto\"H\n\nstateValue\x12\r\n\x05\x62oxes\x18\x01 \x01(\x0c\x12\x0e\n\x06labels\x18\x02 \x01(\x0c\x12\r\n\x05probs\x18\x03 \x01(\x0c\x12\x0c\n\x04\x66\x65\x61t\x18\x04 \x01(\x0c\x62\x06proto3')
)




_STATEVALUE = _descriptor.Descriptor(
  name='stateValue',
  full_name='stateValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boxes', full_name='stateValue.boxes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels', full_name='stateValue.labels', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probs', full_name='stateValue.probs', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feat', full_name='stateValue.feat', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['stateValue'] = _STATEVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

stateValue = _reflection.GeneratedProtocolMessageType('stateValue', (_message.Message,), dict(
  DESCRIPTOR = _STATEVALUE,
  __module__ = 'state_value_pb2'
  # @@protoc_insertion_point(class_scope:stateValue)
  ))
_sym_db.RegisterMessage(stateValue)


# @@protoc_insertion_point(module_scope)
