apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redis-state-store
  namespace: default
  labels:
    app: redis-state-store
spec:
  selector:
    matchLabels:
      app: redis-state-store
  template:
    metadata:
      namespace: kube-system
      labels:
        app: redis-state-store
    spec:
      containers:
      - name: redis-state-store
        image: redis:6.2.6
        command: 
        - redis-server
        - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: example-redis-config
          items:
          - key: redis-config
            path: redis.conf

